import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Manually specify navigation and other key items at the top
    {
      type: 'doc',
      id: 'navigation',
    },
    // Autogenerate sections from specific directories
    {
      type: 'autogenerated',
      dirName: 'vecticum',
    },
    // Autogenerate section with a label
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docusaurus-intro/tutorial-basics',
        },
      ],
    },
    // Catch-all for any remaining documents
    // {
    //   type: 'autogenerated',
    //   dirName: '.', // Root directory
    // },
  ],
};

export default sidebars;